version: 2.1

docker_defaults: &docker_defaults
  docker:
    - image: circleci/node:10.16.0

commands:
  restore_env:
    description: "Prepares dependencies"
    steps:
      - run: echo "yarn lock JACK"
      - run: cat yarn.lock
      - checkout:
          path: ~/project
      - restore_cache:
          name: Restore node_modules cache
          key: networkjs-{{ .Branch }}-{{ checksum "yarn.lock" }}
  save_env:
    description: "Saves dependencies"
    steps:
      - run: echo "yarn lock JACK"
      - run: cat yarn.lock
      - save_cache:
          name: Save node_modules cache
          key: networkjs-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/

jobs:
  install_dependencies:
    <<: *docker_defaults
    working_directory: ~/project
    steps:
      - checkout
      - run: yarn install
      - save_env
  build:
    <<: *docker_defaults
    working_directory: ~/project
    steps:
      - restore_env
      - run: yarn build
  test:
    <<: *docker_defaults
    working_directory: ~/project
    steps:
      - restore_env
      - attach_workspace:
          at: ~/project
      - run: yarn test
  lint:
    <<: *docker_defaults
    working_directory: ~/project
    steps:
      - restore_env
      - run: yarn lint

workflows:
  version: 2
  test_lint_build:
    jobs:
      - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies
